# Generated by Django 5.0.7 on 2024-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Paciente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
