# Generated by Django 5.0.7 on 2024-07-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
