# Generated by Django 5.0.7 on 2024-07-25 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratorios',
            fields=[
                ('id_Laboratorio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Laboratorio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('Tipo_Muestra', models.CharField(max_length=50, verbose_name='Tipo de Muestra')),
                ('id_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Paciente')),
            ],
        ),
    ]
