# Generated by Django 5.0.7 on 2024-07-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_laboratorios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laboratorios',
            new_name='laboratorio',
        ),
    ]
