# Generated by Django 5.0.7 on 2024-07-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0004_rename_laboratorios_laboratorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='id_Laboratorio',
            new_name='id_Laboratorios',
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id_Cita', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Cita')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Usuario')),
            ],
        ),
    ]
