# Generated by Django 5.0.7 on 2024-07-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0005_rename_id_laboratorio_laboratorio_id_laboratorios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id_Medicamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Medicamento')),
                ('nombre_Medicamento', models.CharField(max_length=50, verbose_name='Nombre')),
                ('presentacion', models.CharField(max_length=50, verbose_name='Presentacion')),
            ],
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='Tipo_Muestra',
            new_name='tipo_Muestra',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fecha_Nacimiento',
        ),
        migrations.CreateModel(
            name='Control_Glucosa',
            fields=[
                ('id_Glucosa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Glucosa')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('glisemia', models.IntegerField(verbose_name='Glisemia')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Control_Hipertension',
            fields=[
                ('id_Hipertension', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Hipertension')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('diastolica', models.IntegerField(verbose_name='Diastolica')),
                ('sistolica', models.IntegerField(verbose_name='Sistolica')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Control_Peso',
            fields=[
                ('id_Peso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Peso')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('Altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMC')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='recetas',
            fields=[
                ('id_Recetas', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Recetas')),
                ('fecha_Emision', models.DateField(verbose_name='Fecha_Emision')),
                ('fecha_Reposicion', models.DateField(verbose_name='Fecha_Reposicion')),
                ('id_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.medicamento', verbose_name='ID_Medicamento')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Usuario')),
            ],
        ),
    ]
