# Generated by Django 5.0.7 on 2024-07-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0006_medicamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recetas',
            new_name='receta',
        ),
    ]
