# Generated by Django 5.0.7 on 2024-07-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0007_rename_recetas_receta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control_Hipertension',
            new_name='Control_Hipertensione',
        ),
    ]
