# Generated by Django 5.0.7 on 2024-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0008_rename_control_hipertension_control_hipertensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(null=True, verbose_name='Cedula'),
        ),
    ]
