# Generated by Django 5.0.7 on 2024-07-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0010_paciente_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Alerta')),
                ('id_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='ID_Paciente')),
            ],
        ),
    ]
