# Generated by Django 5.0.7 on 2024-07-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0014_remove_paciente_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='id_Recetas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salud.receta', verbose_name='ID_Recetas'),
            preserve_default=False,
        ),
    ]
