# Generated by Django 5.0.7 on 2024-07-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0018_rename_id_usuari_paciente_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_usuario',
        ),
    ]
