# Generated by Django 5.0.7 on 2024-07-27 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0020_paciente_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='fecha_Alarma',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha_Alarma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertas',
            name='id_Cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salud.cita', verbose_name='ID_Cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertas',
            name='id_Laboratorios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salud.laboratorio', verbose_name='ID_Laboratorio'),
            preserve_default=False,
        ),
    ]
