# Generated by Django 5.0.7 on 2024-07-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0021_alertas_fecha_alarma_alertas_id_cita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertas',
            old_name='id_alerta',
            new_name='id_alertas',
        ),
    ]
