# Generated by Django 5.0.7 on 2024-07-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0023_rename_id_alertas_alertas_id_alertas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alertas',
            new_name='alarmas',
        ),
        migrations.RenameField(
            model_name='alarmas',
            old_name='id_Alertas',
            new_name='id_Alarmas',
        ),
    ]
