# Generated by Django 5.0.7 on 2024-07-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0026_cita_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id_usuario',
        ),
    ]
