# Generated by Django 5.0.7 on 2024-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0029_laboratorio_id_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='id_Medicamento',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='id_usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='lugar',
            field=models.CharField(default=4, max_length=200, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='receta_medicamento',
            fields=[
                ('id_Receta_Medicamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Receta_Medicamento')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.receta')),
            ],
            options={
                'unique_together': {('receta', 'medicamento')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='lista_Medicamentos',
            field=models.ManyToManyField(through='salud.receta_medicamento', to='salud.medicamento', verbose_name='Lista de Medicamentos'),
        ),
    ]
