# Generated by Django 5.0.7 on 2024-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0030_remove_receta_id_medicamento_medicamento_id_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta_medicamento',
            old_name='dosis',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(default=4, max_length=50, verbose_name='Dosis'),
            preserve_default=False,
        ),
    ]
