# Generated by Django 5.0.7 on 2024-07-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0031_rename_dosis_receta_medicamento_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='medico',
            field=models.CharField(default=4, max_length=50, verbose_name='Medico'),
            preserve_default=False,
        ),
    ]
