# Generated by Django 5.0.7 on 2024-08-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0033_alter_receta_medicamento_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='lista_Medicamentos',
        ),
        migrations.DeleteModel(
            name='receta_medicamento',
        ),
    ]
