# Generated by Django 5.0.7 on 2024-08-03 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0034_remove_receta_lista_medicamentos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id_receta_medicamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Receta_Medicamento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('frecuencia', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.receta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('receta', 'medicamento')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='medicamentos',
            field=models.ManyToManyField(through='salud.RecetaMedicamento', to='salud.medicamento'),
        ),
    ]
