# Generated by Django 5.0.7 on 2024-08-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0035_recetamedicamento_receta_medicamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetamedicamento',
            name='usuario',
        ),
    ]
