# Generated by Django 5.0.7 on 2024-08-06 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0036_remove_recetamedicamento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id_alarma', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Alarma')),
                ('fecha_alarma', models.DateTimeField(verbose_name='Fecha y Hora de la Alarma')),
                ('frecuencia', models.CharField(choices=[('1 minuto', '1 minuto'), ('1 hora', '1 hora'), ('1 día', '1 día'), ('1 semana', '1 semana'), ('1 mes', '1 mes')], max_length=20, verbose_name='Frecuencia')),
                ('medio_notificacion', models.CharField(choices=[('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Medio de Notificación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.paciente', verbose_name='Paciente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['fecha_alarma'],
            },
        ),
    ]
