# Generated by Django 5.0.7 on 2024-08-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0037_alarma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmas',
            name='id_Cita',
        ),
        migrations.RemoveField(
            model_name='alarmas',
            name='id_Laboratorios',
        ),
        migrations.RemoveField(
            model_name='alarmas',
            name='id_Recetas',
        ),
        migrations.RemoveField(
            model_name='alarmas',
            name='id_paciente',
        ),
        migrations.DeleteModel(
            name='Alarma',
        ),
        migrations.DeleteModel(
            name='alarmas',
        ),
    ]
